services:
  logbook:
    image: fastapi/dockerhttpapi
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: dockerhttpapi
    hostname: dockerhttpapi
    expose:
      - 8000
    network_mode: host