# frozen_string_literal: true

source "https://rubygems.org"

gem 'sinatra', '~> 3.0', '>= 3.0.5'
gem 'puma', '~> 6.1', '>= 6.1.1'
gem "rack", "~> 2.2"
gem "rackup", "~> 1.0"
gem "rack-unreloader", "~> 2.1"
