spec:
  template:
    spec:
      containers:
        name: tarot
        resources:
          requests:
            memory: 50Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 100m