apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarot
spec:
  selector:
    matchLabels:
      app: tarot
  template:
    metadata:
      labels:
        app: tarot
    spec:
      containers:
      - name: tarot
        image: nginx
        resources:
          requests:
            memory: 50Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 100m