apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tarot
  labels:
    name: tarot
spec:
  ingressClassName: "nginx"
  rules:
  - host: tarot.devanet
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tarot
            port: 
              number: 8000
