services:
  logbook:
    image: devops/logbook
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: devops-logbook
    hostname: devops-logbook
    expose:
      - 8000
    network_mode: host