services:
  logbook:
    image: devops/logbook
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: devops-logbook
    hostname: devops-logbook
    expose:
      - 8000
    network_mode: host
  database:
    image: postgres:14
    container_name: devops-logbook-database
    hostname: devops-logbook-database
    environment:
      POSTGRES_PASSWORD: deva
    expose:
      - 5432
    network_mode: host